version: "3.1"
services:

    elasticsearch:
      image: elasticsearch:5.4-alpine
      container_name: php-elastic-tutorial-elasticsearch

    php-fpm:
      build: phpdocker/php-fpm
      container_name: php-elastic-tutorial-php-fpm
      working_dir: /application
      volumes:
        - .:/application

